from openpyxl import load_workbook
import html

wb = load_workbook('jobs.xlsx')
ws = wb.active
rows = []
for r in range(2, ws.max_row+1):
    company = ws.cell(row=r, column=1).value
    role    = ws.cell(row=r, column=2).value
    loc     = ws.cell(row=r, column=3).value
    pct     = ws.cell(row=r, column=4).value
    why     = ws.cell(row=r, column=5).value
    linkc   = ws.cell(row=r, column=6)
    url     = linkc.hyperlink.target if linkc.hyperlink else ""
    if company is None:
        continue
    rows.append((company, role, loc, pct, why, url))

def esc(x): return html.escape(str(x if x is not None else ""))

trs = ""
for company, role, loc, pct, why, url in rows:
    pcts = f"{round(pct*100)}%" if isinstance(pct,(int,float)) else esc(pct)
    apply_cell = f'<a href="{esc(url)}" style="color:#1a4fd6;text-decoration:none;font-weight:600;">Open &#10132;</a>' if url else ""
    trs += (
        "<tr>"
        f'<td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-weight:600;">{esc(company)}</td>'
        f'<td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;">{esc(role)}</td>'
        f'<td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;color:#4b5563;">{esc(loc)}</td>'
        f'<td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;text-align:center;font-weight:700;color:#0b804b;">{pcts}</td>'
        f'<td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;color:#4b5563;">{esc(why)}</td>'
        f'<td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;">{apply_cell}</td>'
        "</tr>\n"
    )

doc = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,Helvetica,sans-serif;">
<div style="max-width:760px;margin:0 auto;padding:24px;">
  <h1 style="font-size:20px;color:#16263f;margin:0 0 4px;">Daily PM Jobs &mdash; Israel / Cybersecurity</h1>
  <p style="margin:0 0 18px;color:#6b7280;font-size:13px;">Matched Product Manager roles for 2026-07-03 &middot; {len(rows)} strong match(es)</p>
  <table style="width:100%;border-collapse:collapse;background:#fff;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;font-size:13px;">
    <thead>
      <tr style="background:#16263f;color:#fff;text-align:left;">
        <th style="padding:11px 12px;">Company</th>
        <th style="padding:11px 12px;">Role</th>
        <th style="padding:11px 12px;">Location</th>
        <th style="padding:11px 12px;text-align:center;">Match</th>
        <th style="padding:11px 12px;">Why it fits</th>
        <th style="padding:11px 12px;">Apply</th>
      </tr>
    </thead>
    <tbody>
{trs}    </tbody>
  </table>
  <p style="margin:16px 0 0;color:#9ca3af;font-size:11px;">Generated by job_agent.py. Match scores are keyword-based (no ANTHROPIC_API_KEY set).</p>
</div>
</body></html>"""

with open('digest.html','w',encoding='utf-8') as f:
    f.write(doc)
print(f"digest.html written with {len(rows)} jobs")
