#!/usr/bin/env python3
"""Build digest.html from jobs.xlsx (the file job_agent.py actually writes)."""
import datetime as dt
from openpyxl import load_workbook

wb = load_workbook("jobs.xlsx")
ws = wb.active
rows = list(ws.iter_rows(min_row=2, values_only=False))

jobs = []
for r in rows:
    company = r[0].value
    role = r[1].value
    location = r[2].value
    match = r[3].value
    why = r[4].value
    link_cell = r[5]
    url = link_cell.hyperlink.target if link_cell.hyperlink else ""
    if not company:
        continue
    jobs.append((company, role, location, match, why, url))

today = "2026-07-16"

def esc(s):
    s = "" if s is None else str(s)
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

trs = ""
for company, role, location, match, why, url in jobs:
    pct = f"{round((match or 0) * 100)}%"
    apply = f'<a href="{esc(url)}" style="color:#1A4FD6;text-decoration:none;font-weight:600;">Open &rsaquo;</a>' if url else ""
    trs += f"""      <tr>
        <td style="padding:10px 12px;border-bottom:1px solid #e6e6e6;">{esc(company)}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #e6e6e6;font-weight:600;">{esc(role)}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #e6e6e6;color:#555;">{esc(location)}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #e6e6e6;text-align:center;font-weight:700;color:#0b804b;">{pct}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #e6e6e6;color:#555;">{esc(why)}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #e6e6e6;">{apply}</td>
      </tr>
"""

html = f"""<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f4f5f7;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:760px;margin:0 auto;padding:24px;">
    <h1 style="font-size:20px;color:#16263F;margin:0 0 4px;">Daily PM Jobs &mdash; {today}</h1>
    <p style="font-size:13px;color:#777;margin:0 0 18px;">{len(jobs)} strong match(es) &bull; Product Manager / Cybersecurity &bull; Israel</p>
    <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;background:#fff;border:1px solid #e6e6e6;border-radius:6px;overflow:hidden;font-size:13px;">
      <thead>
        <tr style="background:#16263F;color:#fff;text-align:left;">
          <th style="padding:11px 12px;">Company</th>
          <th style="padding:11px 12px;">Role</th>
          <th style="padding:11px 12px;">Location</th>
          <th style="padding:11px 12px;text-align:center;">Match</th>
          <th style="padding:11px 12px;">Why it fits</th>
          <th style="padding:11px 12px;">Apply</th>
        </tr>
      </thead>
      <tbody>
{trs}      </tbody>
    </table>
    <p style="font-size:11px;color:#999;margin:16px 0 0;">Generated by job_agent.py. Match scores are keyword-based (no ANTHROPIC_API_KEY set for AI scoring).</p>
  </div>
</body>
</html>
"""

with open("digest.html", "w", encoding="utf-8") as f:
    f.write(html)

print(f"digest.html written with {len(jobs)} jobs")
