from openpyxl import load_workbook
import datetime as dt, html

wb = load_workbook('jobs.xlsx')
ws = wb.active
rows = []
for r in range(2, ws.max_row+1):
    company = ws.cell(row=r, column=1).value
    role    = ws.cell(row=r, column=2).value
    loc     = ws.cell(row=r, column=3).value
    match   = ws.cell(row=r, column=4).value
    why     = ws.cell(row=r, column=5).value
    lc      = ws.cell(row=r, column=6)
    url     = lc.hyperlink.target if lc.hyperlink else ''
    if company is None or (isinstance(company,str) and company.startswith('No strong matches')):
        continue
    rows.append((company, role, loc, match, why, url))

today = dt.date.today().strftime('%B %d, %Y')

def esc(x): return html.escape(str(x)) if x is not None else ''

tr = []
for company, role, loc, match, why, url in rows:
    pct = f"{round((match or 0)*100)}%"
    link = f'<a href="{esc(url)}" style="color:#1A4FD6;text-decoration:none;font-weight:600">Apply &rarr;</a>' if url else ''
    tr.append(f"""      <tr>
        <td style="padding:12px 14px;border-bottom:1px solid #eee;font-weight:600;color:#16263F">{esc(company)}</td>
        <td style="padding:12px 14px;border-bottom:1px solid #eee;color:#222">{esc(role)}</td>
        <td style="padding:12px 14px;border-bottom:1px solid #eee;color:#555;font-size:13px">{esc(loc)}</td>
        <td style="padding:12px 14px;border-bottom:1px solid #eee;text-align:center;font-weight:700;color:#0a7d33">{pct}</td>
        <td style="padding:12px 14px;border-bottom:1px solid #eee;color:#555;font-size:13px">{esc(why)}</td>
        <td style="padding:12px 14px;border-bottom:1px solid #eee">{link}</td>
      </tr>""")

html_doc = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:24px;background:#f4f6f9;font-family:Arial,Helvetica,sans-serif">
  <div style="max-width:820px;margin:0 auto;background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)">
    <div style="background:#16263F;padding:22px 26px">
      <h1 style="margin:0;color:#fff;font-size:20px">Daily PM Jobs &mdash; Product Manager / Cybersecurity</h1>
      <p style="margin:6px 0 0;color:#9fb2cc;font-size:13px">{today} &middot; {len(rows)} strong match{'es' if len(rows)!=1 else ''} in Israel</p>
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:14px">
      <thead>
        <tr style="background:#f0f3f8;text-align:left">
          <th style="padding:11px 14px;color:#16263F;font-size:12px;text-transform:uppercase;letter-spacing:.4px">Company</th>
          <th style="padding:11px 14px;color:#16263F;font-size:12px;text-transform:uppercase;letter-spacing:.4px">Role</th>
          <th style="padding:11px 14px;color:#16263F;font-size:12px;text-transform:uppercase;letter-spacing:.4px">Location</th>
          <th style="padding:11px 14px;color:#16263F;font-size:12px;text-transform:uppercase;letter-spacing:.4px;text-align:center">Match</th>
          <th style="padding:11px 14px;color:#16263F;font-size:12px;text-transform:uppercase;letter-spacing:.4px">Why it fits</th>
          <th style="padding:11px 14px;color:#16263F;font-size:12px;text-transform:uppercase;letter-spacing:.4px">Link</th>
        </tr>
      </thead>
      <tbody>
{chr(10).join(tr)}
      </tbody>
    </table>
    <div style="padding:16px 26px;color:#888;font-size:12px;border-top:1px solid #eee">
      Generated by your daily job agent. Matches are scored against your Product Manager / cybersecurity profile.
    </div>
  </div>
</body>
</html>"""

with open('digest.html','w',encoding='utf-8') as f:
    f.write(html_doc)
print(f"Wrote digest.html with {len(rows)} jobs")
